admin:
  cms: sveltiacms # All CMS available https://www.hugolify.io/docs/cms/admin/cms/
  branch: master
  git: github
  repo: owen8877/terraform-ansible-playground
  config:
    id: false # set true to use ID for dir/name files and relation
      
  publish_mode: simple # simple or editorial_workflow
  i18n:
    default_locale: en # master lang for an i18n website
    locales: false # "[en,fr]" for an i18n website
  media:
    media_folder: '/assets/images/uploads'
    public_folder: '/images/uploads'
    audio_max_file_size: 700000 # 700ko
    max_file_size: 700000 # 700ko
    pdf_max_file_size: 5000000 # 5Mo
    specific_filter: false # set true to add a selected filter by image
    video_max_file_size: 5000000 # 5Mo

  # Cloud asset config (optional)
  media_library:
    name: # cloudinary or uploadcare
    config:
      cloud_name: # for cloudinary
      api_key: # for cloudinary
      public_key: # for uploadcare
      tabs: # for uploadcare

  nested:
    depth: 5 # set minimum 2

  # Auth
  auth:
    netlify_identity: false # Add Netlify identity

  preview: false

  # Blocks
  blocks:
    # All blocks available https://www.hugolify.io/docs/blocks/
    enable:
      - alert
      - cta
      - editorial
      - faq
      - figure
      - form
      - information
      - images
      - latest
      - paragraph
      - quote
      - selected
      - title

  # Collections
  collections:
    # Collections (except config, indexes and pages) are automatically added based on Hugo modules config, but you can hide a collection if needed.
    config:
      enable: true
    indexes:
      enable: true
    pages:
      enable: true

      # Override fields of collection fields
      fields:
        - is_page
        - draft
        - title_page
        - description
        - body

  # Fields
  fields:
    # Override fields of hugolify fields
    hero:
      - title
      - text_markdown