- name: Install Certbot and Nginx plugin
  become: true
  apt:
    name:
      - certbot
      - python3-certbot-nginx
    state: present
    update_cache: yes

- name: Obtain SSL certificates and configure Nginx
  become: true
  command: >
    certbot --nginx
    --nginx-ctl /usr/sbin/nginx
    -d test.xdrd.me
    --non-interactive
    --agree-tos
    --email owen+test@xdrd.me
    --redirect

- name: Reload nginx
  become: true
  service:
    name: nginx
    state: reloaded