- name: Download Hugo
  get_url:
    url: https://github.com/gohugoio/hugo/releases/download/v0.125.4/hugo_extended_0.125.4_Linux-64bit.tar.gz
    dest: /tmp/hugo.tar.gz

- name: Create Hugo install directory
  become: yes
  file:
    path: /usr/local/hugo
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Extract Hugo
  become: yes
  unarchive:
    src: /tmp/hugo.tar.gz
    dest: /usr/local/hugo
    remote_src: yes
    # extra_opts: [--strip-components=1]
    creates: /usr/local/hugo/hugo  # Skip if already extracted

- name: Symlink Hugo binary
  become: yes
  file:
    src: /usr/local/hugo/hugo
    dest: /usr/local/bin/hugo
    state: link
    force: yes
