- name: Extract sub_domain from inventory_hostname
  set_fact:
    sub_domain: "{{ inventory_hostname.split('.')[0] }}"

- name: apt
  block:
    - name: Ensure apt packages are updated
      apt: update_cache=yes cache_valid_time=3600
    - name: Install required base packages
      apt:
        name: [nginx, git, curl, ufw, unzip, fail2ban]
        state: present

- include_tasks: uv.yml
  
- name: Enable UFW and open ports
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop: [22, 80, 443, 1337]

- include_tasks: nginx.yml

- include_tasks: docker.yml
