- name: Ensure nginx is running
  service:
    name: nginx
    state: started
    enabled: yes

- name: Remove default site
  block:
    - name: remove file
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
    - name: reload nginx
      service:
        name: nginx
        state: reloaded

- name: Install bot blocker
  block:
    - name: download
      shell: |
        curl -sL https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/install-ngxblocker -o /usr/local/sbin/install-ngxblocker
    - name: chmod
      shell: |
        chmod +x /usr/local/sbin/install-ngxblocker
    - name: install
      shell: |
        /usr/local/sbin/install-ngxblocker -x
    # - name: setup
    #   shell: |
    #     yes | /usr/local/sbin/setup-ngxblocker -x


