- name: Install UV
  shell: "curl -LsSf https://astral.sh/uv/install.sh | sh"

- name: Verify UV is installed
  ansible.builtin.command: uv --version
  register: uv_version
  changed_when: false

- name: Show UV version
  ansible.builtin.debug:
    var: uv_version.stdout