- name: Create project directory
  file:
    path: "/home/{{ ansible_user }}/containers/{{ docker_project_name }}"
    state: directory
    mode: '0755'

- name: Upload docker compose file
  template:
    src: "../docker/{{ docker_project_name }}/compose.yaml.j2"
    dest: "/home/{{ ansible_user }}/containers/{{ docker_project_name }}/compose.yaml"
    mode: '0644'

- name: Upload volume tarball if exists
  copy:
    src: "../docker/{{ docker_project_name }}/volume.tar.gz"
    dest: "/home/{{ ansible_user }}/containers/{{ docker_project_name }}/volume.tar.gz"
  ignore_errors: yes

- name: Check if volume tarball exists
  stat:
    path: "/home/{{ ansible_user }}/containers/{{ docker_project_name }}/volume.tar.gz"
  register: volume_tar

- name: Inflate volume if tarball exists
  unarchive:
    src: "/home/{{ ansible_user }}/containers/{{ docker_project_name }}/volume.tar.gz"
    dest: "/home/{{ ansible_user }}/containers/{{ docker_project_name }}"
    remote_src: yes
  when: volume_tar.stat.exists
