- name: Clone Hugo repo
  git:
    repo: https://github.com/owen8877/terraform-ansible-playground.git
    dest: ~/hugo-site
    update: yes
    recursive: yes
    track_submodules: yes 

- name: Build Hugo site
  shell: |
    HUGO_MODULE_MODE=_vendor /usr/local/bin/hugo
  args:
    chdir: ~/hugo-site/test-site
  notify: Restart nginx
