{{ partial "admin/cms/decapcms/shortcodes/alert.js" }}
{{ partial "admin/cms/decapcms/shortcodes/badge.js" }}
{{ partial "admin/cms/decapcms/shortcodes/blank_link.js" }}
{{ partial "admin/cms/decapcms/shortcodes/blockquote.js" }}
{{ partial "admin/cms/decapcms/shortcodes/button.js" }}
{{ partial "admin/cms/decapcms/shortcodes/details.js" }}
{{ partial "admin/cms/decapcms/shortcodes/map.js" }}
{{ partial "admin/cms/decapcms/shortcodes/twitter.js" }}
{{ partial "admin/cms/decapcms/shortcodes/youtube.js" }}